version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3316:3306"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    networks:
      - zero_network

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    environment:
      TZ: Asia/Shanghai
    ports:
      - "6389:6379"
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass 123456  --appendonly yes"
    privileged: true
    networks:
      - zero_network

networks:
  zero_network: